# Generated by Django 4.0.2 on 2022-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.TextField()),
                ('firstName', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('department', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
