# Generated by Django 4.0.2 on 2022-04-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FacultyNames', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('depID', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.TextField()),
                ('firstName', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('rID', models.TextField()),
                ('bName', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('mID', models.AutoField(primary_key=True, serialize=False)),
                ('mName', models.TextField()),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyNames.faculty')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseTables.professors')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourseTables.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('secID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.TextField()),
                ('courseNumber', models.TextField()),
                ('credits', models.TextField()),
                ('days', models.TextField()),
                ('time', models.TextField()),
                ('waitSize', models.TextField()),
                ('sectionNumber', models.TextField()),
                ('enrollment', models.TextField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseTables.departments')),
                ('Professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourseTables.professors')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourseTables.rooms')),
            ],
        ),
    ]
