# Generated by Django 4.0.2 on 2022-04-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseTables', '0002_tempcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMeeting',
            fields=[
                ('mID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('classNumber', models.TextField()),
                ('sectionNumber', models.TextField()),
                ('className', models.TextField()),
                ('room', models.TextField()),
                ('eventType', models.TextField()),
                ('startTime', models.TextField()),
                ('endTime', models.TextField()),
            ],
        ),
    ]
